### ISSUE TITLE
The library cannot be minified and used in the browser

### ISSUE THREAD

**Issue by jdrew1303** [upwork/node-upwork#13]
The use of `pkginfo` is preventing the api from being used by applications that run in the browser. A simple way of fixing this it to require the `package.json` directly and using that to pull info from. Then when browserify or webpack encounter the `require` they will import it as expected. 

![image](https://cloud.githubusercontent.com/assets/2535432/20822429/8e00681c-b842-11e6-893c-13977a2bf0b4.png)

**Comment by jdrew1303** [comment]
For more info on why Im using it in the browser: Im using it in a Chrome Extension to allow a user to post github issues to Upwork as a job using a chrome extension: 

<img width="1220" alt="the_library_cannot_be_minified_and_used_in_the_browser_ _issue__13_ _upwork_node-upwork" src="https://cloud.githubusercontent.com/assets/2535432/20839563/0ea8b9c6-b8a5-11e6-872c-ee5a698a410a.png">

I'm trying to avoid the use of a server if at all possible (I don't want to store credentials for Upwork as it links to peoples credit cards/ bank accounts, etc). I'd also prefer to use an official client library rather than my own home rolled one (usually have better support for newer apis, etc).

The other alternative is that I make the modifications necessary to support this and issue a pull request if you're ok with that?

**Comment by mnovozhylov** [comment]
the library was developed as a backend one

**Comment by giorgio-zamparelli** [comment]
Hi there, pkginfo is also crashing our backend build with webpack.
Webpack does not pack the node-upwork/package.json inside the backend bundle and then pckinfo will throw the error "Could not find package.json".
You could just require the package.json in your code and get the version attribute from it without using pkginfo.

```const packageJson = require('./package.json')
const version = packageJson.version```

**Comment by mnovozhylov** [comment]
We will take a closer look when it's possible. There is no ETA for this.

**Comment by jdrew1303** [comment]
@giorgio-zamparelli its easier to just fork it, make your changes and publish your own version. 👍 Thats what I did, works like a charm.

**Comment by mnovozhylov** [comment]
Fixed in `v1.3.2`
