### ISSUE TITLE
Access Token & Secret configuration

### ISSUE THREAD

**Issue by oleksiipysanko** [upwork/node-upwork#17]
Hi, thanks for the library

Please, either correct example or implementation of access keys setting for api instance, because it won't work in a way described there

https://github.com/upwork/node-upwork/blob/master/example/example.js#L11 specifies that api instance can be configured with access token & secret straight away. But, in `node-upwork` you have:

```
exports.Upwork = function(key, secret) {
    this.baseUrl = baseUrl + '/api/';
    this.OAuth = new OAuth(key, secret);
}
```

So, access keys get ignored. It'll only work when configured with `setAccessToken`

**Comment by mnovozhylov** [comment]
Hello @oleksiipysanko ,

thank you for the feedback!
We will check and update the example accordingly if needed.

**Comment by mnovozhylov** [comment]
@oleksiipysanko , if access token pair is specified in the config, it will be set here - https://github.com/upwork/node-upwork/blob/master/example/example.js#L102.
