### ISSUE TITLE
Is there any way to create an access token/secret?

### ISSUE THREAD

**Issue by thosakwe** [upwork/node-upwork#19]
Hi! 

Thanks for publishing this library. 

I have a question. If I am testing code, it's (in my opinion) to have to mount an entire HTTP server just to get an access token and secret and authenticate my client.

Is there any way to generate a token and secret on the Upwork developer site? You can do this with Twitter and many other OAuth providers.

Thanks,
Tobe O.

**Comment by mnovozhylov** [comment]
Hello @thosakwe ,

thank you for contacting us!

Sorry, we do not provide any GUI for such reasons. At the same time, you can use any tool that supports OAuth 1.0 authentication and use endpoints specified in the public documentation, section [Authentication](https://developers.upwork.com/#authentication_oauth-10).
