### ISSUE TITLE
upgrade qs in node-upwork 0.0.7

### ISSUE THREAD

**Issue by giorgio-zamparelli** [upwork/node-upwork#25]
running npm audit finds 2 vulnerabilities caused by an outdated qs package dependency within the node-upwork 0.0.7 dependency.
I could not make a Pull Request since the github repo https://github.com/BooBSD/node-upwork mentioned on the npm package node-upwork https://www.npmjs.com/package/node-upwork does not exist anymore or is private.
If the repository doesn't exist anymore we could move node-upwork 0.0.7 inside of this repository.
If the repository it's private the user BooBSD will need to update qs and publish a version 0.0.8 with the fix to npm.

                       === npm audit security report ===                        
                                                                                
┌──────────────────────────────────────────────────────────────────────────────┐
│                                Manual Review                                 │
│            Some vulnerabilities require your attention to resolve            │
│                                                                              │
│         Visit https://go.npm.me/audit-guide for additional guidance          │
└──────────────────────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Denial-of-Service Memory Exhaustion                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ qs                                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >= 1.x                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ node-upwork                                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ node-upwork > qs                                             │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/29                        │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Denial-of-Service Extended Event Loop Blocking               │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ qs                                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >= 1.x                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ node-upwork                                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ node-upwork > qs                                             │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/28                        │
└───────────────┴──────────────────────────────────────────────────────────────┘

**Comment by mnovozhylov** [comment]
@giorgio-zamparelli , thank you for letting us know! We received your request and are going to review and fix if needed, as soon as possible. Please stay tuned.

**Comment by mnovozhylov** [comment]
Fixed in `v1.3.1`
