### ISSUE TITLE
new reply attack error when using the library

### ISSUE THREAD

**Issue by javismiles** [upwork/node-upwork#26]
Hi friends, hoping you can help with this:

We are having an issue in the last weeks and wanted to ask you for advice if possible because we changed nothing in our code and suddenly we are losing all the info.

We are working with your library and upwork api to get details of jobs, and since a few weeks ago we are receiving this error message which every few days, more and more often, is blocking our work completely:

{\"status\":403,\"code\":403,\"message\":\"Duplicate timestamp\\/nonce combination, possible replay attack. Request rejected.\"}}"}

Nothing has changed in our code. We have worked with your API for a long time and suddenly we get this

Calls to get a list of jobs work all great. It's when we request the details that we get this error. We cannot find anywhere in our code where we set timestamps so I guess this may be in the node API itself, in this library, is there anything we can add to our code to prevent this problem? thank you so much, here some details of our call:

- Error Code: 403

- Error Message
[5/28/2019, 2:00:17 AM] {"statusCode":403,"data":"{\"server_time\":1559001617,\"error\":{\"status\":403,\"code\":403,\"message\":\"Duplicate timestamp\\/nonce combination, possible replay attack. Request rejected.\"}}"}

- time of requests: this happens all the time to us, every time we request details of a job the error happens, an example is [5/28/2019, 2:00:17 AM] , but basically happens to us multiple times a day

- method of the request: not sure, the upwork-api node library does the request, and the upwork-api library calles oauth library for authorization, inside oauth library I find this, maybe it's related: 
  this._nonceSize= nonceSize || 32;
  this._headers= customHeaders || {"Accept" : "*/*",
                                   "Connection" : "close",
                                   "User-Agent" : "Node authentication"}
  this._clientOptions= this._defaultClientOptions= {"requestTokenHttpMethod": "POST",
                                                    "accessTokenHttpMethod": "POST"};

also our upwork-api library uses node-upwork library which uses oauth library and these oauth parameters:

exports.OAuth = function(key, secret) { 
this.requestUrl = baseUrl + '/api/auth/v1/oauth/token/request'; 
this.accessUrl = baseUrl + '/api/auth/v1/oauth/token/access'; 
this.key = key; 
this.secret = secret; 
this.version = '1.0'; 
this.callback = null; 
this.signatureMethod = 'HMAC-SHA1'; 
this.nonceSize = 32; 
this.customHeaders = { 
'Accept' : 'application/json', 
'Connection' : 'close', 
'User-Agent': 'Node-Upwork' 
}

**Comment by mnovozhylov** [comment]
@javismiles , please, contact Support Team and provide the full details. So, they can assist you.

**Comment by javismiles** [comment]
thank you, I already did, but they are not helping so far, thank you anyway, all best
