### ISSUE TITLE
/engagements not returning new jobs

### ISSUE THREAD

**Issue by kelonye** [upwork/node-upwork#3]
Good work on the API lib!

So I started working on a new job this week but the resource only returns past engagements. Could this be a problem with the job or will this reflect later?

**Comment by mnovozhylov** [comment]
Hello Mitchel,

thanks for the feedback.
So, you mean you can request the data, but returned data contains an issue, correct? In that case, it is probably not related to the library, and you need to contact apisupport@ to provide them all necessary data for further investigation.

**Comment by kelonye** [comment]
Yeah .. using it at [ehance.co](http://ehance.co). Returned data doesn't contain the new engagement but /teams look okay. Alright, I'll do so thanks.

**Comment by mnovozhylov** [comment]
It could be a cache delay. In that case, you just need to wait.

**Comment by kelonye** [comment]
Awesome.

**Comment by kelonye** [comment]
Damn! I was not paging results.
