### ISSUE TITLE
Issue with npm packaging

### ISSUE THREAD

**Issue by khashayar** [upwork/node-upwork#31]
Whenever I try to run my project on CI env after adding node-upwork dependency, I ran into an issue and the CI process fails when it runs `npm install`. The error reads:

```
npm ERR! path /builds/node_modules/node-upwork
npm ERR! code EISGIT
npm ERR! git /builds//node_modules/node-upwork: Appears to be a git repo or submodule.
npm ERR! git     /builds/node_modules/node-upwork
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.
```

It seems the issue is with the way you are packaging the upwork npm and including the `.git` folder inside it, which is unnecessary. Can you please make sure that `.git` folder is excluded from your npm package?

**Comment by mnovozhylov** [comment]
Thank you for the report! The issue has been fixed in version `1.3.5`.
