### ISSUE TITLE
Jobs search limits records

### ISSUE THREAD

**Issue by a-kh-io** [upwork/node-upwork#35]
I make jobs search query by using upwork-api (for Node) with just one criteria (e.g.):
        var params = {
            'q':'Alfresco',
            'sort':'create_time desc'
        }
And it returns 3 records in results.
When I make the same query by using Upwork Portal (Find Jobs by string 'Alfresco') it returns 6 records.
The same query with "Java" word gives 2560 records by using upwork-api and 4041 records by using Upwork Portal.
Why does API give fewer amount of records than Upwork Portal?

**Comment by mnovozhylov** [comment]
Hi @a-kh-io,
could you please contact our Support Team to track your ticket accordingly? The number of records in the response doesn't seem to be related to the library itself, which is only executes the request and doesn't handle any business logic.
