### ISSUE TITLE
Forbidden: Access for the job opening is forbidden.

### ISSUE THREAD

**Issue by jack-fdrv** [upwork/node-upwork#49]
Hi there, first, thank you for your job, this is really helpfull. 
I got error when i try get details about batch of jobs.
So first i get get 20 latest jobs with @upwork/node-upwork-oauth2/lib/routers/jobs/search.js
Make an array of new jobs ids so it looks like
`['~01723d93f0c2c8e127', '~01723d93f0c2c8e122', '~01723d93f0c2c8e121'] ` etc
Then run **getSpecific** and provide that array with ";" by @upwork/node-upwork-oauth2/lib/routers/jobs/profile.js
So i instead of just run API req inside loom for each job i do only 1 api req.
But i got this error very often: 
`{"server_time":1676019520,"error":{"status":403,"code":403,"message":"Forbidden: Access for the job opening is forbidden."}}`

And i dont know which one job id it cause to exclude it from my array and there is no way how i can get the list of latest jobs but only for those which i have access to.

Any idea how i can fix it?

**Comment by mnovozhylov** [comment]
Not related to the functionality of the library. You probably don't have access to the job(s).
