### ISSUE TITLE
101% hire rate?

### ISSUE THREAD

**Issue by jack-fdrv** [upwork/node-upwork#50]
Here an example of client data of this job post http://www.upwork.com/jobs/~013d895c4ebcf160b3
![image](https://user-images.githubusercontent.com/4230282/218255415-0d49a779-86e0-479b-b751-390cad9d45f0.png)

But how it is possible that **op_tot_jobs_posted** less then **op_tot_jobs_filled**?
{
  op_adjusted_score: '4.986150499',
  op_tot_jobs_posted: '93',
  op_state: 'ON',
  op_timezone: 'UTC-05:00 Eastern Time (US & Canada)',
  op_tot_charge: '50000',
  op_contract_date: 'April 10, 2013',
  op_tot_jobs_open: '2',
  op_tot_fp_asgs: '76',
  op_tot_hours: '26395.33333386',
  op_tot_asgs: '152',
  op_country: 'Canada',
  op_tot_jobs_filled: '94',
  op_city: 'Toronto'
}

**Comment by mnovozhylov** [comment]
@jack-fdrv, the response data are not controlled by the library. Please, don't open issues here. If you need help regarding this, please, contact Support Team
