### ISSUE TITLE
TypeError: Cannot read property 'auth_user' of undefined

### ISSUE THREAD

**Issue by nunoarruda** [upwork/node-upwork#6]
I've tried to run your node upwork-api example (https://developers.upwork.com/?lang=node#getting-started_libraries-and-tools) but it returns the error "TypeError: Cannot read property 'auth_user' of undefined" when I insert the verifier (check screenshot).

I did inserted the consumerKey and consumerSecret properly.

I'm on a Mac using a latest version of OSX and using node v5.6.0 and npm v3.6.0.
<img width="682" alt="screen shot 2016-02-15 at 12 36 51" src="https://cloud.githubusercontent.com/assets/1189149/13040088/92d10ab2-d3e2-11e5-875d-9fd81f30a53b.png">

**Comment by mnovozhylov** [comment]
@nunoarruda , this is not a library issue - you are not auth-ed. Please, make sure your key was enabled and you followed authentication process accordingly.

**Comment by nunoarruda** [comment]
My key is enabled. 
<img width="477" alt="screen shot 2016-02-15 at 12 56 33" src="https://cloud.githubusercontent.com/assets/1189149/13040202/1b846a60-d3e4-11e5-9617-899661d23891.png">

Still getting the error...

**Comment by mnovozhylov** [comment]
works on v0.12.10 and on earlier version - v0.10.25
you must check your environment and make sure you follow all steps
