### ISSUE TITLE
new message center api

### ISSUE THREAD

**Issue by arieljake** [upwork/node-upwork#8]
Is this supported? Looks like `upwork-api/lib/routers/mc` with methods like `getTrays` is the old message center api. Correct?

**Comment by mnovozhylov** [comment]
@arieljake , please follow our changelog at https://developers.upwork.com/api-changelog.html, this API will be deprecated soon

**Comment by arieljake** [comment]
@mnovozhylov I know about the new API. Why don't we want to support it in this library?

**Comment by mnovozhylov** [comment]
@arieljake , not sure why you decided that we won't include them in future versions

**Comment by arieljake** [comment]
Because you closed this issue

**Comment by mnovozhylov** [comment]
@arieljake , there is no issue - current version still supports mc api, support for new Message API will appear in next versions those not released yet, i.e. is not a part of this library

**Comment by mnovozhylov** [comment]
support has been added in v1.2.0
